version: '3.7'

services:
  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  mongo-data:
