ktor:
  application:
    modules:
      - com.parizmat.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  issuer: "http://localhost:8080"

  realm: "ktor sample app"
